### ISSUE TITLE
Handling of overpass errors (timeout, limit)

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte#10]
Overpass queries that lead to a timeout create empty results. Zooming in and deselecting/reselecting the filter does not help. Timeouts should lead to a reset of the filter and a message like "Too many results, please zoom in and try again".

Or maybe this issue will be resolved as soon as we have an url?

**Comment by ValorNaram** [comment]
This issue is obsolete now because we do not use Overpass anymore. But error handling is on my To Do list.

**Comment by ValorNaram** [comment]
With my latest commit error handling improved.
