### ISSUE TITLE
Updating privacy policies

### ISSUE THREAD

**Issue by ValorNaram** [babykarte/babykarte#11]
Due to the server switch we need to update our privacy policy in all languages we support.

Status of the Update:

| Privacy Policy file           | language | status |
| :----------------------------- | :----------- | :------- |
| `privacypolicy-de.md`    | german    | **Final** |
| `privacypolicy-en.md`    | english     | **Translated** |
| `privacypolicy-fr.md`      | french      | **Translated** |

**Comment by ValorNaram** [comment]
@Discostu36 could you please proofread https://github.com/babykarte/babykarte/blob/devel/privacypolicy-de.md ?

**Comment by Discostu36** [comment]
> Bei sonstigen Interaktionen mit der Babykarte (Laden der Web-App, Verschiebung der Karte, Klicks auf interaktive Elementen und weitere Anwendungsmöglichkeiten) werden Daten an unseren Server everest.openstreetmap.de bzw. babykarte.openstreetmap.de gesendet. Diese Daten sind für den Betrieb der Babykarte notwendig. Diese Daten für sich allein sind keine personenbezogenen Daten. In keinster Weise speichert der Server diese Daten oder gibt sie an Dritte weiter. 

I don't think this is correct. I imagine that the server is writing IP addresses into log files and these log files are stored for a certain amount of time. And German courts have decided that IP addresses are personal data.

**Comment by ValorNaram** [comment]
> Bei sonstigen Interaktionen mit der Babykarte (Laden der Web-App, Verschiebung der Karte, Klicks auf interaktive Elementen und weitere Anwendungsmöglichkeiten) werden Daten an unseren Server [everest.openstreetmap.de](https://everest.openstreetmap.de) bzw. [babykarte.openstreetmap.de](https://babykarte.openstreetmap.de) gesendet. Diese Daten sind für den Betrieb der Babykarte notwendig und werden nicht gespeichert. Dieser Server führt allerdings Logs über eingehende Verbindungen aber diese lassen nicht die zur Identifizierung notwendigen Daten zu. Somit können wir Dir keine Auskunft über Daten geben, die Dein Browser an uns gesendet hat. Wir würden schon daran scheitern Dich im ganzen Datenstrom zu finden.

Weird... IP addresses are personal data... weird. But ok, I changed the paragraph. Does it look better now? It is understandable?

Please consider the definition for Logs and the section "Kontaktaufnahme Deines Browsers mit Servern".

**Comment by Discostu36** [comment]
> Dieser Server führt allerdings Logs über eingehende Verbindungen aber diese lassen nicht die zur Identifizierung notwendigen Daten zu.

I don't understand this sentence.

**Comment by ValorNaram** [comment]
Dieser Server führt Logs über eingehende Verbindungen, doch mit diesen lassen keine Rückschlüsse auf das Verhalten einzelner Nutzer zu.

It's better now? I cannot access the logs anyway.

**Comment by ValorNaram** [comment]
Uploaded the corrected version of it. Should we start to translate?

**Note: I excluded the use of Nominatim for various reasons. From Nominatim we've got the addresses.**

**Comment by Discostu36** [comment]
> Uploaded the corrected version of it. Should we start to translate?

Yes

**Comment by Discostu36** [comment]
I have trouble translating this sentence because I'm not sure what is meant:
>Diese Ressourcen werden von Entwicklern den Cache-Servern manuell zur Verfügung gestellt.

**Comment by ValorNaram** [comment]
It simply means that developers upload and distribute most used internet resources (e.g. libraries like JQuery) over Servers to other developers.

Developers then include resources from this Severs so Browsers just have to download them ones which leads to better loading performance of websites.

**Comment by Discostu36** [comment]
So, to make it a bit more clear, the sentence could also read:
> Diese Ressourcen werden von den Entwicklern der Cache-Server über diese zur Verfügung gestellt. 

Or am I still understanding it incorrectly?

**Comment by ValorNaram** [comment]
You understand it **correctly**

**Comment by Discostu36** [comment]
Done

**Comment by ValorNaram** [comment]
This issue will be closed during releasing process.

**Comment by Discostu36** [comment]
@ValorNaram You still have to prepare the French translation if I'm not mistaken?

**Comment by ValorNaram** [comment]
I will just approach our friend from france when we are finish with v3.0 so we have to do just the french translation. So this issue will be part of the releasing process.

As long as we did not finish v3.0 as long I will put this on hold.

**Comment by ValorNaram** [comment]
I also can copy and paste some sections if they were not updated.

**Comment by ValorNaram** [comment]
@NicolasGrosjean We got space inclusive database on a server sponsored by FOSSGIS. The requests to our own database are incredible faster than to the Overpass API. So changes in our Privacy Policy were necessary and we're asking you to translate it to french. The parts not changed during our rewrite process remain unchanged and in french in file `privacypolicy-fr.md`. We changed 88% of our privacy policy but not the difficult parts :)

**Short and simple:** Please translate all english phrases in file `privacypolicy-fr.md` into french.

**Comment by NicolasGrosjean** [comment]
I have translated _Baby Map_ by _Babykarte_ as it appears as title of the web page.
I have found very strange that the name of the application is not the same as in German in the private policy.

I have also found strange the browser start contacting a cache server with Google and Digital Ocean. Is it only for Google Chrome ?

**Comment by ValorNaram** [comment]
> I have also found strange the browser start contacting a cache server with Google and Digital Ocean. Is it only for Google Chrome ?

This applies to all Browsers and the JQuery and Leaflet library will be requested over these connections.

**Comment by ValorNaram** [comment]
- [ ] Converting all privacy policies to HTML.
