### ISSUE TITLE
Add shop=bakery

### ISSUE THREAD

**Issue by carstenhag** [babykarte/babykarte#12]
Hey, some bakeries are only for picking up something, but at some you can sit down, drink a coffee and enjoy the view.

This could be added under a food filter.

**Comment by Discostu36** [comment]
According to the wiki, you should add a second node with `amenity=cafe `if the bakery is also a cafe.

A second possibility, used mainly in Germany, is to add `cafe=yes` to the bakery. If we want to support this, we can add these to the cafe filter.

**Comment by ValorNaram** [comment]
> A second possibility, used mainly in Germany, is to add cafe=yes to the bakery. If we want to support this, we can add these to the cafe filter.

Do we want this?

**Comment by ValorNaram** [comment]
> A second possibility, used mainly in Germany, is to add cafe=yes to the bakery. If we want to support this, we can add these to the cafe filter.

Okay, okay, I will add this.

**Comment by ValorNaram** [comment]
Or wait. `cafe=yes` is not specified.

https://taginfo.openstreetmap.org/keys/?key=cafe#values

https://wiki.openstreetmap.org/wiki/Key:cafe


This is not okay, I hate people doing that. I can do something like `tags ? 'cafe'` but now I'm unsure because with programming comes great responsibility.

**Comment by Discostu36** [comment]
It is documented in German wiki.

https://wiki.openstreetmap.org/wiki/DE:Tag:shop%3Dbakery#Optionale_Tags

I understand that this tag lacks proper documentation, has never been officially proposed and is only used in one part of the world. But 1.000 use cases is quite a lot and there is no harm done in supporting it. It is not our job as map creators to educate the mappers.

**Comment by ValorNaram** [comment]
> It is not our job as map creators to educate the mappers.

But we can do that. I already contacted the author. I will see what I can do, need to think about it.

`or tags ? 'cafe'`

I hope the community accepts this tag.
