### ISSUE TITLE
Make it possible to fix menu items

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte#15]
The menu items on the left should not only work with mouse over. This is already quite irritating on Desktop but a no-go on mobile. It should be possible to open them with a click/touch and that they stay open until they are manually closed or another one is opened.

**Comment by ValorNaram** [comment]
Then I would suggest that it works only with a click when you already find the hover behaviour confusing. Doing it this way, doing it with javascript, making it clickable, solves also some issues on mobile including the one you described.

**Comment by ValorNaram** [comment]
**Done**. Does it look good now?
