### ISSUE TITLE
Changing baby friendliness tab

### ISSUE THREAD

**Issue by ValorNaram** [babykarte/babykarte#16]
In #14 we discuss a new PDV scheme and I want to remove the _baby friendliness_ tab and put content to the _home_ tab. For that I need to compress information so users can see with just a short look what kind of features the POI has. I will convey this information in an one-line to the users.

**Some real world examples:**
[Node 1838908696](https://www.openstreetmap.org/node/1838908695): Changing table &#8231; Partially stroller friendly
[Node 736843477](https://www.openstreetmap.org/node/736843477): Changing table (No fees, multi-purpose room) &#8231; Highchairs &#8231; Stroller friendly
[Node 6763949405](https://www.openstreetmap.org/node/6763949405): &nbsp;
[Node 6699012254](https://www.openstreetmap.org/node/6699012254): Highchairs &#8231; Partially stroller friendly &#8231; Kids area

**Some fictive examples:**
Changing table (Fees, female toilet) &#8231; Kids area (outside) &#8231; Highchairs
Stroller friendly &#8231; Kids area (inside, supervised)
Changing table (No fees, female toilet) &#8231; Baby feeding (female) &#8231; Highchairs

**Why?**
Putting it into the _home_ tab enables users to get information faster (reducing clicks and reading time). This style (one-liners) gives brief information to the hands of the users.

**Comment by Discostu36** [comment]
I like the idea, but am not quite sure how your idea will look in the end product. Maybe you can provide some (made up) screenshots.

**Comment by ValorNaram** [comment]
Of course the baby friendliness tab will be removed.

**Comment by Discostu36** [comment]
How would descriptions be provided, like used in 1838908695?

**Comment by ValorNaram** [comment]
Like in the baby friendliness tab but a different implementation.

**Comment by ValorNaram** [comment]
Now it's done! Fetch the newest version of `devel` and see how it looks :)

**Comment by Discostu36** [comment]
Not very pretty for POIs with much information:

![image](https://user-images.githubusercontent.com/30999326/66866421-8b713e00-ef99-11e9-9f78-f3944ad6b927.png)

And you've removed the text for the contact information (again). We've already discussed this some months ago. The information should be visible as text, not hidden behind icons.

I can only repeat myself: When redesigning Babykarte, have a look at how other maps have tackled the same problems. Do it like them. Only do it differently if you have good reasons for it.

**Comment by ValorNaram** [comment]
> Not very pretty for POIs with much information:

Yes, I'm working on how I can compress information so PDVs don't get overloaded. And I think I will remove support for the `description` tag but I'm not quite sure about that yet.

> Only do it differently if you have good reasons for it.

There are good reasons. Long touch on a symbol on mobile gives you the url and hovering over it on desktop and then looking to the left bottom of the page because there the Browser will display the url. I can also develop a tooltip that shows up when hovering on desktop or long touch on mobile (Equivalent to right click) right below the item (contact icon).

**Comment by ValorNaram** [comment]
In commit https://github.com/babykarte/babykarte/commit/6336b5d46e914cde852a65f186982404f2aa9b6d I removed the tabs and did some other design changes. As we agreed on we put all tabs in block mode (all after one). On mobile there will be the option to slide to top to show all information. On both desktop and mobile version the information for the baby friendliness will be atop right under the icons (contact icons and baby friendliness icons).

In addition to the icons we also show a text version after all icons.

**Comment by Discostu36** [comment]
Some feedback:
- Contact information is gone, should return
- Baby friendliness icons should always be there and color coded (green, yellow, red, grey)
- Move share icon to the top (next to edit)
- Move operator and decription to the end of the pop-up, without need of an extra click (similarly to how Osmand does it)

**Comment by ValorNaram** [comment]
Done, please have a look.

**Comment by Discostu36** [comment]
Icon behaviour doesn't seem to be changed
![Screenshot_20191117-071912_Firefox](https://user-images.githubusercontent.com/30999326/69003921-b210f480-090a-11ea-96c8-cef6d8156934.jpg)

**Comment by ValorNaram** [comment]
> Baby friendliness icons should always be there and color coded (green, yellow, red, grey)

So do you want the grey ones always to be displayed?

**Comment by Discostu36** [comment]
Yes 😊

**Comment by ValorNaram** [comment]
> Baby friendliness icons should always be there and color coded (green, yellow, red, grey)

**Done**
