### ISSUE TITLE
Filters buggy

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte#17]
There is something amiss with the filters in devel.

Steps to reproduce:
1. Select cafés filter
2. Select a café
3. Select restaurant filter
4. Select a restaurant

Nothing happens. When selecting the POI item on the left, the last café is shown.

This also happens the other way round, with restaurant first and café second.

**Comment by ValorNaram** [comment]
This bug is known to me and has something to do with #14 , the function which enables the effect on the marker when clicking on it.
