### ISSUE TITLE
Address calculation not working?

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte#18]
![image](https://user-images.githubusercontent.com/30999326/66867089-db043980-ef9a-11e9-8f73-78f274879a97.png)
Address calculation doesn't seem to work. POI is in a building that has full address.
https://www.openstreetmap.org/node/6352019317

**Comment by ValorNaram** [comment]
Normally Nominatim would have provided us with this kind of data but we switched from that and I forgot to develop something for cases like these. I forgot to develop a script that can handle address gathering from buildings because I forgot about the whole address gathering.

**Comment by ValorNaram** [comment]
Ok, forgot another thing.

The database we access does not contain all data (here: buildings) so address calculation won't work by just relaying on the database. I will reactivate the code for nominatim and will readd the Nominatim section to the privacy policies. So there's no work for you. You have to work on #14 and that's huge work @Discostu36

**Comment by ValorNaram** [comment]
The problem of working with two different OSM database at the same time :)
