### ISSUE TITLE
add amenity=fast_food

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte#2]
I think we should put amenity=fast_food on the map to cover for example McDonald's restaurants. I'd like to get your feedback if we should include these into the restaurant filter or if you think this should be a separate filter.

**Comment by ValorNaram** [comment]
> even though I mapped stroller stuff :D

@carstenhag We don't show elements with the key `stroller` on the map. It just works in combination with the filters inclusive their keys we describe [in the wiki](https://wiki.osm.org/Babykarte).

**Comment by carstenhag** [comment]
Yeah, I had thought something wrong. Nevermind

**Comment by ValorNaram** [comment]
Which colour should the new filter have? I accept rgb (not rgba), colour names and hashes.

**Comment by carstenhag** [comment]
Hmm, I'd just have a general food/restaurant section and then let the user filter by restaurants or fast food amenities.

**Comment by carstenhag** [comment]
Especially as we add more shops etc, see https://github.com/babykarte/babykarte/issues/12

**Comment by ValorNaram** [comment]
> I think we should put amenity=fast_food on the map to cover for example McDonald's restaurants.

**Added**

**Comment by carstenhag** [comment]
thanks!
