### ISSUE TITLE
Evaluate clothes=*

### ISSUE THREAD

**Issue by sdicke** [babykarte/babykarte#21]
In the case of this [node](https://www.openstreetmap.org/node/6981571167) I observed an behavior in the Babykarte devel branch:
This is a clothes shop which offers, according to information visible from outside, only clothes for women. That is offers clothes for women, is tagged.

To search there for clothes for babies would be probably not successfully.

A solution could be to exclude clothes shops, where is tagged, which clothes are offered, from display, if babies is not contained in the value string.

**Comment by Discostu36** [comment]
This is a new bug, thanks for noticing. Originally, this filter ony showed shops with clothes for babies and children, like you suggest.

**Comment by ValorNaram** [comment]
**Fixed in backend**
