### ISSUE TITLE
Address display at playgrounds

### ISSUE THREAD

**Issue by sdicke** [babykarte/babykarte#22]
Obviously the house number search often fails at playgrounds (with Babykarte devel branch), resulting in display<code> $Streetname ?</code>. Examples: [Velen-Velen](https://babykarte.openstreetmap.de/devel/#17&51.895059542378576&6.986242532730103), [Bochum-Linden](https://babykarte.openstreetmap.de/devel/#17&51.421122000191055&7.18005895614624) and [Düsseldorf-Kaiserswerth](https://babykarte.openstreetmap.de/devel/#16&51.3022061763096&6.74288034439087).

**Comment by sdicke** [comment]
The same phenomenon exists with parks.

**Comment by Discostu36** [comment]
This is normal behaviour, these locations don't have a real address. But maybe it would be less irritating if instead of a question mark for the number only the street name was displayed.
