### ISSUE TITLE
Chang behaviour of external links

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte#25]
Instead of
 `<a href="http://poi-kiel.de" style="text-align:justify;">http://poi-kiel.de</a>` 
external links should be opened with
`<a href="http://poi-kiel.de" target="_blank" rel="noopener" style="text-align:justify;">http://poi-kiel.de</a>`

**Comment by Discostu36** [comment]
`rel="noopener"` is missing

**Comment by ValorNaram** [comment]
> `rel="noopener"` is missing

What does this relation mean?

**Comment by Discostu36** [comment]
It should be added to links with `target=_blank` for security reasons. See for example [this website for more information](https://mathiasbynens.github.io/rel-noopener/).

**Comment by ValorNaram** [comment]
Weird... CORS does not apply there? I think the Policy rules every Cross-Site interaction. Will add that.
