### ISSUE TITLE
Feel free to test v3.0

### ISSUE THREAD

**Issue by ValorNaram** [babykarte/babykarte#27]
Hello public,

we are inviting you to check out https://babykarte.openstreetmap.de/devel  and to report us what you think.

**Comment by NicolasGrosjean** [comment]
It is very strange to be able to edit the introduction text.

![image](https://user-images.githubusercontent.com/13560473/69882559-d8eb0580-12d0-11ea-8432-3c1a8a7ffab9.png)

**Comment by NicolasGrosjean** [comment]
When we change language, we lose the filters

**Comment by NicolasGrosjean** [comment]
The highchair of the restaurant [Gourmet Bar](https://babykarte.openstreetmap.de/devel/#19&45.19085000529348&5.712592899799347) are not displayed.
Is my OSM contribution wrong ?

**Comment by NicolasGrosjean** [comment]
Formatting issue in German (and French see my PR) with sharing
![image](https://user-images.githubusercontent.com/13560473/69883038-a4784900-12d2-11ea-9adc-9ec1975953a5.png)
![image](https://user-images.githubusercontent.com/13560473/69883062-bf4abd80-12d2-11ea-9b47-c948096c6a91.png)
![image](https://user-images.githubusercontent.com/13560473/69883077-d093ca00-12d2-11ea-9a5c-9c1133fc632e.png)

**Comment by NicolasGrosjean** [comment]
If the zipcode or the city is in the OSM data, the other one is not found.

For example the restautant :

- [Le Petit Bouchon Gascon](https://babykarte.openstreetmap.de/devel/#19&45.19085000529348&5.712592899799347) has only a city tag ([POI](https://www.openstreetmap.org/node/3415688730))
- [L'Aiguillage](https://babykarte.openstreetmap.de/devel/#19&45.19085000529348&5.712592899799347) has only a zipcode tag ([POI](https://www.openstreetmap.org/node/2143123838))

**Comment by NicolasGrosjean** [comment]
That's all for issues after test.

Thanks a lot for this new version, it is amazing how it is faster and more beautiful especially on mobile.

**Comment by ValorNaram** [comment]
> It is very strange to be able to edit the introduction text.

This is an easter egg.

**Comment by ValorNaram** [comment]
Everything should work now! [Devel](https://babykarte.openstreetmap.de/devel) deployed.

**Comment by ValorNaram** [comment]
> Is my OSM contribution wrong

@NicolasGrosjean No! Babykarte has good support for implicit values like `highchar=2` or `highchair=3`. Explicit values are `highcair=yes` and `highchair=no`. Implicit values are represented with a `*` and also this needs a reference in the language files because with e.g. `%s highchairs available` it is possible to give the user the number of highcairs available. The reference was just missing in all language reference files (LRF's). By a `*` represented values now have the color green. You are still a good mapper :smile: 

PS: We do not have somethin like `%s highchairs available` for `highchair` in the LRF's but - theoretically - the architecture allows us that as you can see for `min_age` and `max_age`. Practically no one asked me to do this.
