### ISSUE TITLE
Proudly provided by OpenStreetMap

### ISSUE THREAD

**Issue by ValorNaram** [babykarte/babykarte#32]
I play with the idea to let our customers know on every click of a POI that the data is coming from OpenStreetMap with the possibility to click on a link to get redirected to the OpenStreetMap website for the language user has currently selected e.g. https://openstreetmap.de or https://openstreetmap.fr ...

**Comment by Discostu36** [comment]
Do you have a concept how you'd like to do it? Maybe create a mock-up that we can discuss?

**Comment by ValorNaram** [comment]
Why did you close that issue?

**Comment by Discostu36** [comment]
By mistake

**Comment by ValorNaram** [comment]
> Do you have a concept how you'd like to do it?

Not yet.

**Comment by ValorNaram** [comment]
@Discostu36 What do you think when you see the changes on https://babykarte.openstreetmap.de/devel/?

**Comment by Discostu36** [comment]
Too prominent for my taste.

**Comment by ValorNaram** [comment]
I set the font size to 10px now, see the [devel](https://babykarte.openstreetmap.de/devel) version.
