### ISSUE TITLE
Unknown baby friendliness  icons for non-food POIs

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte#38]
There are still gray baby friendliness icons shown for POIs that are not part of the food group. I tried to fix this myself but I didn't find where in the code I can specify that a symbol should only be shown if the value is not undefined.

![grafik](https://user-images.githubusercontent.com/30999326/69901088-2624b100-137d-11ea-9e84-8a1855f2f376.png)

**Comment by ValorNaram** [comment]
Don't you want to know if a paediatrican is stroller friendly or has a changing table?

**Comment by Discostu36** [comment]
I do, but only when it's tagged, not the grey symbols

**Comment by Discostu36** [comment]
But maybe this is stupid? I have to think about it...

**Comment by ValorNaram** [comment]
> I do, but only when it's tagged, not the grey symbols

The idea to have not the grey symbols is stupid because that makes it less consistent.

**Comment by Discostu36** [comment]
Ok, but the other way around: This should not be excluding tagged features. If somebody decides to add a kids_area tag to a doctor's office, it should ne allowed, no matter what symbols we are showing.

**Comment by ValorNaram** [comment]
Sorry, I do not get it. What do you mean exactly?

**Comment by Discostu36** [comment]
If I understand your code correctly at the moment there are only two possibilities:

1) The icon is always shown, if there is data or not
2) The icon is never shown, even if the tag is used on the POI.

I don't want 2) to happen.

**Comment by ValorNaram** [comment]
Yes and what's the point?

**Comment by Discostu36** [comment]
Well, does it happen or doesn't it?

**Comment by ValorNaram** [comment]
> The icon is always shown, if there is data or not

Yes, right.

> Well, does it happen or doesn't it?

You interpreted my code correctly. Yes, it does work like this. The icon is always shown (colour coded) or never shown.

**Comment by ValorNaram** [comment]
> I don't want 2) to happen.

So the behaviour of showing stroller and changing table icons and the showing of text information for both should stay also for paediatricians?

**Comment by Discostu36** [comment]
Icons and text information should always be shown if defined! If not, then only grey stroller and changing table icons for paediatricians.

**Comment by ValorNaram** [comment]
> Icons and text information should always be shown if defined! If not, then only grey stroller and changing table icons for paediatricians.

That's the behaviour we currently have with with all POI's in _health_ category (pediatrician, midwifes and birthing centers) and of course all POI's in _eat_ category (cafés, restaurants, fast food restaurants).
