### ISSUE TITLE
Clustering 

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte#40]
@simonpoole has mentioned the clustering of markers in the German forum. I know that @ValorNaram is not a fan of that idea but I also think that it would be useful, especially when zoomed out or in areas with a high density of POIs.

**Comment by ValorNaram** [comment]
The question is: Does clustering really improve the user experience because it just hides markers but does nothing to also reach them faster. Both methods - clustering or not clustering (as it is currently) - require the user to zoom. I do not see an advantage for our users.

**Comment by simonpoole** [comment]
The advantage of any approach (either limiting min zoom or clustering) is that it stops the users browser from standing still.

**Comment by Discostu36** [comment]
I'm against limiting zoom levels too much because some filters (e.g. midwives) contain very few POIs, so they are only useful when zoomed out quite a bit while others like cafés in urban areas are only useful when zoomed in as much as possible.

When you look at the [real world example of leaflet.markercluster](https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html), you can see several advantages for our users:

1) It is possible to zoom out very far and see at a glance if there are more playgrounds in Lübeck or in Kiel.
2) In very densely mapped areas you can click at a cluster and the markers are separated from each other. This solves two problems:
a) The baby friendliness rating symbol is, at the moment, sometimes obscured by another marker
b) Especially on mobile it is sometimes not easy to select the right marker.

So I'm very in favour of using the leaflet.markercluster or some other similar solution.

**Comment by ValorNaram** [comment]
Are you happy with the implementation? See the deployment of devel

**Comment by Discostu36** [comment]
I like it.

**Comment by patzi** [comment]
Hi i tried out the cluster on devel https://babykarte.openstreetmap.de/devel/#19&54.3425&10.1370 you can not zoom in closer but markers are still clustered. If you click on the cluster the markers are not shown on the exact position as you can see on https://babykarte.openstreetmap.de/#16&54.33849618697729&10.137891769409181
So there are two possible ways to solve it:
- show the exact position of markers when clicking on the cluster
- disable the clustering if you are on max zoom

**Comment by Discostu36** [comment]
For me, the ideal solution would be to only disable clustering on the highest zoom level for playground equipment because it seems to be the only kind of POI where exact location is relevant. But at the moment all the POIs are in the same cluster group, so this would only work if we put the playground equipment in its own.

@ValorNaram What are your thoughts on this?

**Comment by ValorNaram** [comment]
> POI where exact location is relevant

The exact location is always relevant. We use the map to orientate ourselves in the world or to know where a place is located. Since my latest commit Babykarte deactivates the clustering at zoom level 17 (close to 19 because 17 is also used for street level navigation) for all POI's.
