### ISSUE TITLE
info popup

### ISSUE THREAD

**Issue by mondstern** [babykarte/babykarte#42]
in this infofield you could still see when the entered data is visible. it is done manually. it works automatically. it takes 1 hour. it takes 24 hours. something like that would be informative. thanks in advance.

**Comment by ValorNaram** [comment]
Which infofield do you mean? Do you mean when the data in our own database gets updated?

**Comment by mondstern** [comment]
You've got this to choose from upstairs: I / the globe / input the / the square to select and on the right side a character. If I click on the i on the far left, the baby map will be explained. This popup, this page I mean. At the direct provider osm map named https://farmshops.eu/ for example " How often are the data compared and what is their current status? At the moment, the data is manually synchronized with a script at regular intervals ™ . An automatic comparison is planned. Last data comparison: 10.12.2019 around 11 o'clock." That's what I mean

I hope you understand me ?

**Comment by ValorNaram** [comment]
Yes, you want information about when our data gets updated. I guess our database gets updated each hour or after one day. Need to speak to the admin :)

@Discostu36 How do we integrate that information? Any idea? E.g.

> Babykarte helps parents of infants and toddlers to search for changing tables, playgrounds etc. It also shows the baby friendliness of cafes and restaurants. Data update every x hour

**Comment by ValorNaram** [comment]
The database gets updated every hour. The update takes usually 15 minutes because we need not only to fetch newest updates but also to preprocess them. So after ca. 15 minutes after the hour the database has been refreshed by script and Babykarte shows new data.

Expect newest and fresh content at 13:15, 14:15, 15:15, 16:15, 17:15, 18:15 and so on.

**Comment by Discostu36** [comment]
Only interesting for OSM editors,  so on the last line of the info box:

_Last data update: 2019-12-24 17:00_

It should be the time of data generation, not the time of finished import.

**Comment by ValorNaram** [comment]
> It should be the time of data generation, not the time of finished import.

 E.g. 14:15 last data creation.

**Comment by ValorNaram** [comment]
I have a suggestion for the text:

> Data update: fifteen minutes after each hour

**Comment by Discostu36** [comment]
Is it possible to get real data from the server about the update? So that the user can see if updates are broken?

**Comment by ValorNaram** [comment]
It's technically possible but the update is usually successful because each algorithm and each SQL query has been validated. What is possible that Babykarte gets informed about when new data is available. Since Babykarte (Frontend and Backend) and DMS (database management system inclusive update scripts) are hard seperated, I need to write a connector that reads the log.

**Comment by ValorNaram** [comment]
Or I ask the admin about it what is the best solution for that. But maybe reading the logs is best

**Comment by mondstern** [comment]
> Only interesting for OSM editors, so on the last line of the info box:
> 
> _Last data update: 2019-12-24 17:00_

Last data update: 2019-12-24

**Comment by ValorNaram** [comment]
Would put that into a new website with new url to show such information. It does not belong to our "Help section".

**Comment by mondstern** [comment]
I don't mind that either. It would be good to know.

**Comment by ValorNaram** [comment]
Since import errors are unlikely and that it is unsecure to read logs from within a web script, I will use javascript to calculate the time the database received its last update.
