### ISSUE TITLE
Reduce coordinate precision in URLs

### ISSUE THREAD

**Issue by claudiush** [babykarte/babykarte#43]
Right now URLs of Babykarte contain coordinates with 14 positions after the decimal point: https://babykarte.openstreetmap.de/#17&51.34277715085972&12.372429370880129
This is overkill and makes it hard for humans to at least somewhat glance at the URL. URLs on www.openstreetmap.org just have 5 positions after the decimal. I suggest to align with that.

**Comment by Discostu36** [comment]
I agree

**Comment by ValorNaram** [comment]
The site osm.org has just three and Babykarte has now four after the dot.

**Comment by goldfndr** [comment]
Actually, the site osm.org varies the precision based on the zoom level.
