### ISSUE TITLE
Three popup issues

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte#46]
![Screenshot_20200229-220349_Firefox](https://user-images.githubusercontent.com/30999326/75615049-7d364f80-5b3f-11ea-9fc8-f957d73bc690.jpg)

Three problems in this screenshot:
1. `changing_table=no` is not shown
2. `kids_area:description=` is not shown
3. Marker looses focus on map move. Either keep focus or close popup

**Comment by ValorNaram** [comment]
> Marker looses focus on map move. Either keep focus or close popup

This is technical. Every map move that does force Babykarte to clear the map and to download the data new for the view leading also in a refresh of map elements that do not need a refresh. If I can create a working model of loading just data the user hasn't downloaded before for the view then this error can be fixed.

**Comment by ValorNaram** [comment]
> changing_table=no is not shown

Was not defined in the LRF's (language reference files).

> kids_area:description= is not shown

There was no entry for that available in the PDV template for baby friendliness.
