### ISSUE TITLE
kids_area=no not shown

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte#47]
`kids_area=no` is not shown in PDV:

![grafik](https://user-images.githubusercontent.com/30999326/75772287-f1454300-5d4b-11ea-9bb8-693138a37d5b.png)

**Comment by ValorNaram** [comment]
**Fixed!** See my [commit](https://github.com/babykarte/babykarte/commit/4bbc5d52d8c3ca30f312df0b14a960ee232d8227) to see how did I fix it. This commit is clean and good to learn how to understand my code @Discostu36 .
