### ISSUE TITLE
Improve search results

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte#48]
Now that our search function will become the major part for user interaction, we should also tackle improving the regular search results:

- [x] Sort results by proximity to map center (at the moment, first result can be thousands of km away)
- [x] Add street name to address to distinguish different POIs with the same name in the same city (e.g. McDonald's, H&M) **or** add `branch=` behind name if available (I can't decide what's the better solution)

**Comment by Discostu36** [comment]
Sorting not fixed
![Screenshot_20200309-225727_Firefox](https://user-images.githubusercontent.com/30999326/76261056-70111300-6259-11ea-95c0-58c71002aaca.jpg)

**Comment by ValorNaram** [comment]
I am passing he parameters `lat` and `lon` to Photon by Komoot. See https://photon.komoot.de/api/?q=McDonald%27s&lat=54.32308131652028&lon=10.139915941399524&limit=5&lang=en

Seems to be a bug on their site. Their repo is at https://github.com/komoot/photon/

PS: It worked when I tested before uploading and then suddenly not.

**Comment by Discostu36** [comment]
Results are better (still not perfect) with forced high location bias: `&location_bias_scale=10`

**Comment by ValorNaram** [comment]
@Discostu36 See line _124_ in file `js/ui.js` (recent commit). Feel free to change the value of `location_bias_scale` to something else. I set it to _20_.

**Comment by Discostu36** [comment]
range is 0.1 to 10, see [readme](https://github.com/komoot/photon/blob/master/README.md#search-with-location-bias)

**Comment by ValorNaram** [comment]
Grrrrrr but thank you
