### ISSUE TITLE
Dropping support of Key:diaper

### ISSUE THREAD

**Issue by ValorNaram** [babykarte/babykarte#54]
I will drop Key:diaper support for this poorly defined key in a future release of Babykarte. I hope this makes the code also cleaner because Babykarte does not support normalizing tagging schemes.

**Comment by Discostu36** [comment]
Will this also improve performance or is this for maintainability only?

**Comment by ValorNaram** [comment]
Maintainability only

**Comment by Discostu36** [comment]
Well, as you are the only one still maintaining anything here I won't try to talk you out of it 😃

**Comment by ValorNaram** [comment]
We need to reactivate Babykarte e.g. the search is not working because Komoot changed its service url.

**Comment by ValorNaram** [comment]
Done for master (https://github.com/babykarte/babykarte/commit/f429a74e1ae5b3b0d1856a2ac4b417fb8c788b79) & devel (https://github.com/babykarte/babykarte/commit/9ad615189111630f7f539d7ba92c96d60aafa4e9)
