### ISSUE TITLE
Why is the no-filter overlay contenteditable?

### ISSUE THREAD

**Issue by ygra** [babykarte/babykarte#56]
Most people probably won't notice that they can edit the text, although ... what for? It also shows squiggly underlines for words the browser things are misspelled, though.
![image](https://user-images.githubusercontent.com/1692688/112765853-77938d80-900f-11eb-9fc1-8ff57362092b.png)

**Comment by ValorNaram** [comment]
Just for fun so people can have fun :) But maybe time to remove it.
