### ISSUE TITLE
Add playground equipment

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte#7]
This was a very long unsubmitted issue that was deleted because my system froze. So now it's a bit less carefully written as it was intended, feel free to ask questions if anything remains unclear.

The tags [`playground`](https://wiki.openstreetmap.org/wiki/Key:playground) and [`playground:`](https://wiki.openstreetmap.org/wiki/Key:playground:) are often used but rendered nowhere. We should be the first project to do so.

Because this is a complicated endeavor, we should tackle it in small steps:

- [x] If a `leisure=playground` has tags with the scheme `playground:*=yes`, these should be added to the baby friendliness tab under a heading "**Playground features:**"
- [x] If a playground is an area (or multipolygon), Babykarte should look if there are nodes inside of it with the `playground=*` tag. If yes, these should be added to the list as well
- [x] <s> On the highest zoom level, playgrounds should be shown as areas instead of markers. Only the border of the area should be clickable to show the popup.</s>
- [x] On the highest zoom level, nodes with the tag `playground=` should be shown as little dots. A click on the dot should open a popup that tells what kind of equipment this is (e.g.: Title: "Slide", subtitle: "Playground equipment")
- [x] [The wiki page](https://wiki.openstreetmap.org/wiki/Key:playground) of the `playground=` tag shows many tags for additional information that can be tagged. The most important of these ([consult taginfo!](https://taginfo.openstreetmap.org/keys/playground#combinations)) should be added to the popup as well.

**Notes:**
- If a playground uses both tagging schemes at once, it has to be made sure that this does not result in duplicates in the list
- If there is more than one kind of playground equipment in the same area, the number should be part of the list in the popup (e.g. "Slide 2x", or, even better, "2 slides")
- The equipment popups should be simpler than the current ones, only one page: Title, subtitle, bullet points

**Comment by ValorNaram** [comment]
> On the highest zoom level, playgrounds should be shown as areas instead of markers. Only the border of the area should be clickable to show the popup.

On the highest zoom level you see already the boundaries of an object. So drawing an extra area shouldn't be needed here.

**Comment by ValorNaram** [comment]
> If there is more than one kind of playground equipment in the same area, the number should be part of the list in the popup (e.g. "Slide 2x", or, even better, "2 slides")

Is this really important to know? I think most parents wouldn't bother if there are two or more. But anyway SQL seems automatically to do a clean up so just one entry will be shown. This happens when postgres looks what kind of playground equipments are laying in the playground.

**Comment by ValorNaram** [comment]
> On the highest zoom level, nodes with the tag playground= should be shown as little dots. A click on the dot should open a popup that tells what kind of equipment this is (e.g.: Title: "Slide", subtitle: "Playground equipment")

Support added with one difference: Not only on the highest zoom level playground equipment will be shown but also on all other zoom level. In public Telegram group "OSM de" you said that was a good thing.
