### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by ValorNaram** [babykarte/babykarte#8]
The POIs behind the links tend to have the best dataset to test Babykarte features on. You can use this collection of links to debug and validate new features.

- [local](http://localhost:8080/#19&54.33396741701923&10.122873812979378), [live](https://babykarte.github.io/#19&54.33396741701923&10.122873812979378) &nbsp; Restaurant with some data in the baby friendliness tab.
- [local](http://localhost:8080/#19&54.3474881322212&10.140878587917543), [live](https://babykarte.github.io/#19&54.3474881322212&10.140878587917543) &nbsp; POI "Forstbaumschule" with a rich set of data.
- [local](http://localhost:8080/#19&51.5615645&12.9846290),  [live](https://babykarte.github.io/#19&51.5615645&12.9846290) &nbsp; Hospital "Torgau".
- [local](http://localhost:8080/#19&54.324401566139166&10.124362438982645), [live](https://babykarte.github.io/#19&54.324401566139166&10.124362438982645) &nbsp; Cafè "Liebling" with a rich dataset.
- [local](http://localhost:8080/#18&54.32542770245289&10.12296035874897), [live](https://babykarte.github.io/#18&54.32542770245289&10.12296035874897) &nbsp; Nappy with a rich dataset.
- [local](http://localhost:8000/#15&52.4009309&13.0591397), [live](https://babykarte.github.io/#15&52.4009309&13.0591397) &nbsp; Potsdam has a very good dataset available for testing.
- [local](http://localhost:8080/#19&47.62184500528181&-122.10279844701292), [live](http://babykarte.github.io/#19&47.62184500528181&-122.10279844701292) &nbsp; A playground with equipment mapped seperate in Seattle, USA.
- [local](http://localhost:8080/#15&54.3235354&9.6885383), [live](http://babykarte.github.io/#15&54.3235354&9.6885383) &nbsp; A playground with equipment mapped (not seperate).
- [local](http://localhost:8080/#19&54.32228820781011&10.126189291477205), [live](https://babykarte.github.io/#19&54.32228820781011&10.126189291477205) &nbsp; A cafe with `changing_table=limited`.

**Comment by ValorNaram** [comment]
I will move this to the CONTRIBUTION.md soon to have relevant dev info on one spot.

**Comment by Discostu36** [comment]
Don't forget to update the links, they still have the old domain.

**Comment by ValorNaram** [comment]
Now you will find the content of the first message [here](https://github.com/babykarte/babykarte/blob/devel/CONTRIBUTING.md) and after the merge to the master branch also [here](https://github.com/babykarte/babykarte/blob/master/CONTRIBUTING.md)
